apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Ashiqur"
  #annotations:
    #backstage.io/techdocs-ref: url:https://github.com/backstage123/node-repo/tree/master
    
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
